import { IASTScope } from '../Visitor/Visitor';

export interface ASTNode {
  $assign_pattern?: boolean;
  $fuse_classInitializers?: Array<ASTNode>;
  $fuse_class_declaration_visited?: boolean;
  $fuse_decoratorForClassIdentifier?: string;
  $fuse_decoratorsCaptured?: boolean;
  $fuse_decoratorsProcessed?: boolean;
  $fuse_visited?: boolean;
  $transpiled?: boolean;
  alternate?: ASTNode;
  base?: ASTNode;
  chain?: ASTNode;
  consequent?: ASTNode;
  decorators?: Array<ASTNode>;
  elementTypes?: Array<ASTNode>;
  elements?: Array<ASTNode>;
  expressions?: Array<ASTNode>;
  initializer?: ASTNode;
  literal?: ASTNode;
  moduleReference?: ASTNode;
  prefix?: boolean;
  returnType?: ASTNode;
  scope?: IASTScope;
  shorthand?: boolean;
  specifiers?: Array<ASTNode>;
  test?: ASTNode;
  type: ASTNodeType;
  typeAnnotation?: ASTNode;
  typeName?: ASTNode;
  loc?: { end: { column: number; line: number }; start: { column: number; line: number } };

  imported?: ASTNode;
  members?: Array<ASTNode>;
  method?: boolean;
  source?: ASTNode;

  JSXElement?: ASTNode;

  argument?: ASTNode;
  attributes?: Array<ASTNode>;
  children?: Array<ASTNode>;
  closingElement?: ASTNode;
  openingElement?: ASTNode;

  abstract?: boolean;
  accessibility?: string;
  arguments?: Array<ASTNode>;
  async?: boolean;
  body?: ASTNode | Array<ASTNode>;
  callee?: ASTNode;
  computed?: boolean;
  declaration?: ASTNode;
  declarations?: Array<ASTNode>;
  declare?: boolean;
  exported?: ASTNode;
  expression?: any;
  generator?: boolean;
  id?: ASTNode;
  implements?: Array<ASTNode>;
  init?: null | ASTNode;
  key?: ASTNode;
  kind?: string;
  left?: ASTNode;
  local?: ASTNode;
  name?: any;
  object?: ASTNode;
  operator?: string;
  parameter?: ASTNode;
  params?: Array<ASTNode>;
  properties?: Array<ASTNode>;
  property?: ASTNode;
  right?: ASTNode;
  static?: boolean;
  superClass?: ASTNode;
  value?: any;

  quasi?: ASTNode;
  quasis?: Array<ASTNode>;
  tag?: ASTNode;
  tail?: ASTNode;
}
export type ASTNodeType =
  | 'AbstractClassProperty'
  | 'AbstractKeyword'
  | 'AbstractMethodDefinition'
  | 'AnyKeyword'
  | 'ArrayExpression'
  | 'ArrayPattern'
  | 'ArrayType'
  | 'ArrowFunctionExpression'
  | 'AsExpression'
  | 'AssignmentExpression'
  | 'AssignmentPattern'
  | 'AsyncKeyword'
  | 'AwaitExpression'
  | 'BigIntKeyword'
  | 'BigIntLiteral'
  | 'BinaryExpression'
  | 'Block'
  | 'BlockStatement'
  | 'BooleanKeyword'
  | 'BreakStatement'
  | 'CallExpression'
  | 'CallSignatureDeclaration'
  | 'CatchClause'
  | 'ClassBody'
  | 'ClassDeclaration'
  | 'ClassExpression'
  | 'ClassImplements'
  | 'ClassProperty'
  | 'ConditionalExpression'
  | 'ConditionalType'
  | 'ConstructSignatureDeclaration'
  | 'ConstructorType'
  | 'ContinueStatement'
  | 'DebuggerStatement'
  | 'DeclareFunction'
  | 'DeclareKeyword'
  | 'Decorator'
  | 'DoWhileStatement'
  | 'EmptyBodyFunctionExpression'
  | 'EmptyStatement'
  | 'EnumDeclaration'
  | 'EnumMember'
  | 'ExportAllDeclaration'
  | 'ExportAssignment'
  | 'ExportDefaultDeclaration'
  | 'ExportKeyword'
  | 'ExportNamedDeclaration'
  | 'ExportSpecifier'
  | 'ExpressionStatement'
  | 'ExternalModuleReference'
  | 'ForInStatement'
  | 'ForOfStatement'
  | 'ForStatement'
  | 'FunctionDeclaration'
  | 'FunctionExpression'
  | 'FunctionType'
  | 'HTMLClose'
  | 'HTMLOpen'
  | 'Identifier'
  | 'IfStatement'
  | 'Import'
  | 'ImportDeclaration'
  | 'ImportDefaultSpecifier'
  | 'ImportEqualsDeclaration'
  | 'ImportExpression'
  | 'ImportNamespaceSpecifier'
  | 'ImportSpecifier'
  | 'ImportType'
  | 'IndexSignature'
  | 'IndexedAccessType'
  | 'InferType'
  | 'InterfaceBody'
  | 'InterfaceDeclaration'
  | 'InterfaceHeritage'
  | 'IntersectionType'
  | 'JSDocNullableType'
  | 'JSDocUnknownType'
  | 'JSXAttribute'
  | 'JSXClosingElement'
  | 'JSXClosingFragment'
  | 'JSXElement'
  | 'JSXEmptyExpression'
  | 'JSXExpressionContainer'
  | 'JSXFragment'
  | 'JSXIdentifier'
  | 'JSXMemberExpression'
  | 'JSXOpeningElement'
  | 'JSXOpeningFragment'
  | 'JSXSpreadAttribute'
  | 'JSXSpreadChild'
  | 'JSXText'
  | 'LabeledStatement'
  | 'Line'
  | 'Literal'
  | 'LiteralType'
  | 'LogicalExpression'
  | 'MappedType'
  | 'MemberExpression'
  | 'MetaProperty'
  | 'MethodDefinition'
  | 'MethodSignature'
  | 'ModuleBlock'
  | 'ModuleDeclaration'
  | 'NamespaceExportDeclaration'
  | 'NeverKeyword'
  | 'NewExpression'
  | 'NonNullExpression'
  | 'NullKeyword'
  | 'NumberKeyword'
  | 'ObjectExpression'
  | 'ObjectKeyword'
  | 'ObjectPattern'
  | 'OptionalChain'
  | 'OptionalExpression'
  | 'OptionalType'
  | 'ParameterProperty'
  | 'ParenthesizedType'
  | 'PrivateKeyword'
  | 'Program'
  | 'Property'
  | 'PropertySignature'
  | 'ProtectedKeyword'
  | 'PublicKeyword'
  | 'QualifiedName'
  | 'ReadonlyKeyword'
  | 'RestElement'
  | 'RestType'
  | 'ReturnStatement'
  | 'SequenceExpression'
  | 'SpreadElement'
  | 'StaticKeyword'
  | 'StringKeyword'
  | 'Super'
  | 'SwitchCase'
  | 'SwitchStatement'
  | 'SymbolKeyword'
  | 'TaggedTemplateExpression'
  | 'TemplateElement'
  | 'TemplateLiteral'
  | 'ThisExpression'
  | 'ThisType'
  | 'ThrowStatement'
  | 'TryStatement'
  | 'TupleType'
  | 'TypeAliasDeclaration'
  | 'TypeAnnotation'
  | 'TypeAssertion'
  | 'TypeLiteral'
  | 'TypeOperator'
  | 'TypeParameter'
  | 'TypeParameterDeclaration'
  | 'TypeParameterInstantiation'
  | 'TypePredicate'
  | 'TypeQuery'
  | 'TypeReference'
  | 'UnaryExpression'
  | 'UndefinedKeyword'
  | 'UnionType'
  | 'UnknownKeyword'
  | 'UpdateExpression'
  | 'VariableDeclaration'
  | 'VariableDeclarator'
  | 'VoidKeyword'
  | 'WhileStatement'
  | 'WithStatement'
  | 'YieldExpression'
  | 'module'
  | 'script';
